In [1]:
import numpy as np

In [2]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.zeros(4).reshape(2, 2)

array([[0., 0.],
       [0., 0.]])

In [12]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones([3, 5])[:, :]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
A = np.array([[2, 1, 1], [0, 0, 2], [1, 4, 9]])

In [54]:
A

array([[2, 1, 1],
       [0, 0, 2],
       [1, 4, 9]])

In [55]:
A.T

array([[2, 0, 1],
       [1, 0, 4],
       [1, 2, 9]])

In [56]:
np.linalg.det(A)

-14.000000000000004

In [57]:
A1 = np.linalg.inv(A)

In [58]:
A1.dot(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
b

array([9])

In [71]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

np.linalg.solve(a, b)

array([2., 3.])

In [70]:
a = [[3]]
b = [9]
np.linalg.solve(a, b)

array([3.])

In [73]:
np.linalg.matrix_power(a, 2)

array([[10,  5],
       [ 5,  5]])

In [75]:
np.linalg.matrix_rank(a)

2